insert into address(street,township,city) values('No.D-36,Between 27×28th Sts,Between 84×85th Sts','Chan Aye Thar Zan','Mandalay');
insert into address(street,township,city) values('No.3, 56th Street Quarter (7)','Hlaing','Yangon');
insert into address(street,township,city) values('19st,Between 80x81 sts','Aungmyaytharzan','Mandalay');
insert into address(street,township,city) values('Between 35x36 sts,Between 84x85 sts','Maharaungmyay','Mandalay');
insert into address(street,township,city) values('41st,Between 75x76 sts ','Maharaungmyay','Mandalay');

insert into customer (name,address_id,phone,email) values ('mahar swe',1,'02-57494','maharswe@gmail.com');
insert into customer (name,address_id,phone,email) values ('Andrew',2,'02-522494','andrewnyar@gmail.com');
insert into customer (name,address_id,phone,email) values ('Andrew',3,'02-93322494','andrewnyar@gmail.com');

insert into customer (name,address_id,phone,email) values ('Sophia',2,'02-7694','sophia@gmail.com');
insert into customer (name,address_id,phone,email) values ('William',2,'01-234343','William@gmail.com');
insert into customer (name,address_id,phone,email) values ('John',2,'01-993423333','John@gmail.com');
insert into customer (name,address_id,phone,email) values ('Arnel',2,'02-3453453','Arnel@gmail.com');
insert into customer (name,address_id,phone,email) values ('Upul Sampah',3,'02-645323','UpuSampahanlin@gmail.com');
insert into customer (name,address_id,phone,email) values ('banyar',4,'02-828342','banyar@gmail.com');
insert into customer (name,address_id,phone,email) values ('san lin',5,'02-22333345','sanlinanlin@gmail.com');

insert into category(name) values ('Diary');
insert into category(name) values ('Snacks');
insert into category(name) values ('Drinks');
insert into category(name) values ('Fruits');
insert into category(name) values ('Vegetables');
insert into category(name) values ('Cleaning');
insert into category(name) values('Others');

insert into product (name,dt_price,ws_price,category_id) values('Milk',2500,2000,1);
insert into product (name,dt_price,ws_price,category_id) values('Eggs',2200,2000,1);
insert into product (name,dt_price,ws_price,category_id) values('Butter',4000,3800,1);
insert into product (name,dt_price,ws_price,category_id) values('Cheese',3000,2500,1);
insert into product (name,dt_price,ws_price,category_id) values('Yogurt',1200,1000,1);
insert into product (name,dt_price,ws_price,category_id) values('Candy',700,500,2);
insert into product (name,dt_price,ws_price,category_id) values('Dried Fruit',1500,1000,2);
insert into product (name,dt_price,ws_price,category_id) values('Popcorn',800,500,2);
insert into product (name,dt_price,ws_price,category_id) values('Sunflower Seeds',1200,1100,2);
insert into product (name,dt_price,ws_price,category_id) values('Tiger Beer',2500,2200,3);
insert into product (name,dt_price,ws_price,category_id) values('Su Coffee',3500,3300,3);
insert into product (name,dt_price,ws_price,category_id) values('Lemon Juice',3200,3000,3);
insert into product (name,dt_price,ws_price,category_id) values('Red Bull',1000,700,3);
insert into product (name,dt_price,ws_price,category_id) values('Red level',42000,40000,3);
insert into product (name,dt_price,ws_price,category_id) values('Super Tea',300,250,3);
insert into product (name,dt_price,ws_price,category_id) values('Aye thar yar Wine',4500,4000,3);
insert into product (name,dt_price,ws_price,category_id) values('Apple',1500,1300,4);
insert into product (name,dt_price,ws_price,category_id) values('Avocados',1500,1200,4);
insert into product (name,dt_price,ws_price,category_id) values('Cherries',2000,1700,4);
insert into product (name,dt_price,ws_price,category_id) values('Grapefruit',1500,1300,4);
insert into product (name,dt_price,ws_price,category_id) values('Watermelon',2000,1800,4);
insert into product (name,dt_price,ws_price,category_id) values('Broccoli',2000,1750,5);
insert into product (name,dt_price,ws_price,category_id) values('Chilies',500,400,5);
insert into product (name,dt_price,ws_price,category_id) values('Onions',3200,3000,5);
insert into product (name,dt_price,ws_price,category_id) values('Potatoes',1000,1000,5);
insert into product (name,dt_price,ws_price,category_id) values('Tomatos',1200,1100,5);
insert into product (name,dt_price,ws_price,category_id) values('Air fresher',4000,3800,6);
insert into product (name,dt_price,ws_price,category_id) values('Garbage bag',700,500,6);
insert into product (name,dt_price,ws_price,category_id) values('Glass cleaner',1300,1200,6);
insert into product (name,dt_price,ws_price,category_id) values('Dish soap',500,400,6);
insert into product (name,dt_price,ws_price,category_id) values('Laundry soap',2200,2000,6);
insert into product (name,dt_price,ws_price,category_id) values('Body Wash soap',2200,2000,6);